server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql123
  cloud:
    inetutils:
      # 忽略指定网卡（支持正则），假设你的电脑有 VM 那么该选项是非常有用的一个选项
      ignored-interfaces:             # 忽略 docker0 网卡以及 veth 开头的网卡
      - docker0
      - veth.*
      preferred-networks:             # 使用指定网络地址，选择 eth0 网卡，当然也可以直接写 IP （192.168）
      - eth0
